<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <!-- Recursos incrustados (imágenes, etc.) -->
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <!-- Excluir los archivos de scores de los recursos (ya que no se necesitan embebidos) -->
  <ItemGroup>
    <AvaloniaResource Remove="Assets\scores\**" />
    <AvaloniaXaml Remove="Assets\scores\**" />
    <Compile Remove="Assets\scores\**" />
    <EmbeddedResource Remove="Assets\scores\**" />
    <None Remove="Assets\scores\**" />
  </ItemGroup>

  <!-- Copiar los archivos de sonido al directorio de salida -->
  <ItemGroup>
    <None Update="Assets\sounds\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="$(AvaloniaVersion)" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
  </ItemGroup>
</Project>